### ISSUE TITLE
Trying to get your script working on Raspberry Pi 4

### ISSUE THREAD

**Issue by akucio** [RobertWojtowicz/miscale2garmin#10]
Hi :)

That's a great idea to export Xiaomi data to Garmin. I'm using Fenix 6 Pro so I prefer to store all my data in Garmin connect app.

I'm using Raspberry Pi 4 with latest Debian Bullseye, everything is updated :) Scale model is exact the same - XMTZC05HM. Firmware version from Xiaomi app is 1.0.0.12.

I've run into few problems:
1. bluetooth.service had a bit different path of ExecStart - ExecStart=/usr/**libexec**/bluetooth/bluetoothd so i just added "--noplugin=sap". There seems no bluetooth folder in lib directory, it exists only in libexec.
2. I used armv6 version of bodycomposition (i'm not sure it's the right one).
3. I can't run any script without sudo.
4. scanner_ble.py reads data only when I'm standing on the scale, I thought it should work 15 minutes from using it (maybe I misunderstood your readme :)). The data it showed into console was: 88.65;466;1646906408;2022-3-10 11:0:8
5. export_garmin.py shows that there is no user with the given weight. I've edited the script with maxweight 95 and minweight 75 so it should work.
6. import_ble.sh shows No BLE data from scale or incomplete but I think that's because export_garmin.py isn't working.

Please don't mind if some of the questions are obvious - I'm a beginner linux user and a beginner java programmer so I may do something wrong... :)

**Comment by RobertWojtowicz** [comment]
Hi,

"I can't run any script without sudo."

chmod +x bodycomposition import_ble.sh scanner_ble.py export_garmin.py ?

**Comment by akucio** [comment]
I did that before as readme stated, I tried to do it again but still scanner_ble runs only with sudo. Without it shows an error:

```
pi@raspberrypi:~/miscale2garmin-3.0 $ python3 scanner_ble.py 
Mi Body Composition Scale 2 Garmin Connect v3.0 (scanner_ble.py)

Traceback (most recent call last):
  File "/home/pi/miscale2garmin-3.0/scanner_ble.py", line 56, in <module>
    scale.run()
  File "/home/pi/miscale2garmin-3.0/scanner_ble.py", line 47, in run
    scanner.start()
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 20, error: Permission Denied)
```

**Comment by RobertWojtowicz** [comment]
chmod +x /usr/local/lib/python3.9/dist-packages/bluepy/btle.py

**Comment by akucio** [comment]
Ok, that helped. Scanner runs ok (still reading data only when standing on scale, that's the way it should run?):

```
pi@raspberrypi:~/miscale2garmin-3.0 $ python3 scanner_ble.py 
Mi Body Composition Scale 2 Garmin Connect v3.0 (scanner_ble.py)

* Starting BLE scan:
  BLE device found with address: 3c:95:09:xx:xx:xx, non-target device
  BLE device found with address: 5c:ca:d3:xx:xx:xx <= target device
  BLE device found with address: 5c:ca:d3:xx:xx:xx <= target device
  BLE device found with address: 5c:ca:d3:xx:xx:xx <= target device
* Reading BLE data complete, finished BLE scan
87.95;483;1646919031;2022-3-10 14:30:31
```

But then I've got problem with export:
```
pi@raspberrypi:~/miscale2garmin-3.0 $ python3 export_garmin.py 
Mi Body Composition Scale 2 Garmin Connect v3.0 (export_garmin.py)
There is no user with the given weight, check users section in export_garmin.py
```

my users section looks like this:

`users = [User("male", 175, '01-01-1985', "xxx@xxx", "xxx", 95, 60)]`

so measured 87,95 should be within given range - form 60 to 95. How to check what's wrong? :)
